---
title: "05-N_target"
author: ''
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 4.5, fig.width = 6.5, tidy=FALSE)
```


"2017-07-31 14:06:51 PDT"

`r getwd()`  

`r Sys.time()`




# Weighted

```{r weighted_grouped, fig.height = 5, fig.width = 7}
library(rmap)
data(weighted_example_cohort_sample)
xxx = weighted_example_cohort_sample
head(xxx)
e = xxx$e
t = xxx$t
r = xxx$r
t_star = 10
data(weighted_example_target_sample)
head(weighted_example_target_sample)
target_category = weighted_example_target_sample$category
category = xxx$category
design = list(target_category = target_category, category = category)
cutoffs = c(0, 0.20, 1)
risk_group = list(cutoffs = cutoffs)
r_summary = "mean"
confidence_level = 0.95
N_bootstraps = 100
N_cores = 1
verbose = FALSE
set.seed(5)
rmap_answers = rmap(e, t, r, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = length(e)^(-1/3)
risk_group = list(epsilon = epsilon)
individual = rmap_individual(e, t, r, t_star, design, risk_group,
                             N_bootstraps, confidence_level, N_cores, verbose)
the_message = paste("rmap on weighted sample")
grid.arrange(textGrob(the_message), 
             pretty_risk_plot_fn(rmap_answers), 
             pretty_roc_plot_fn(rmap_answers), 
             pretty_individual_risk_plot_fn(individual),
             ncol = 2)
```

```{r}
df = data.frame(table(target_category))
N_target = df$Freq
names(N_target) = df$target_category
design = list(category = category, N_target = N_target)
design
str(design)
```

```{r}
risk_group = list(cutoffs = cutoffs)
set.seed(5)
rmap_answers = rmap(e, t, r, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = length(e)^(-1/3)
risk_group = list(epsilon = epsilon)
individual = rmap_individual(e, t, r, t_star, design, risk_group,
                             N_bootstraps, confidence_level, N_cores, verbose)
the_message = paste("rmap on weighted sample calling N_target")
grid.arrange(textGrob(the_message), 
             pretty_risk_plot_fn(rmap_answers), 
             pretty_roc_plot_fn(rmap_answers), 
             pretty_individual_risk_plot_fn(individual),
             ncol = 2)
```

