---
title: "06-rmap_individual-examples"
author: ''
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 4.5, fig.width = 6.5, tidy=FALSE)
```


"2017-08-01 15:31:02 PDT"

`r getwd()`  

`r Sys.time()`



# Random Sample
```{r random_sample, message = FALSE, eval = TRUE, fig.height = 5, fig.width = 7}
library(rmap)
data(random_sample_example)
xxx = random_sample_example
head(xxx)
e = xxx$e
t = xxx$t
r = xxx$r
t_star = 10
design = "random_sample"
epsilon = length(e)^(-1/3)
N_bootstraps = 100
set.seed(1)
individual = rmap_individual(e, t, r, t_star, design, epsilon, N_bootstraps)
pretty_individual_risk_plot(individual)
```


# Two-stage sample

```{r two_stage_sample_grouped, fig.height = 5, fig.width = 7}
library(rmap)
data(two_stage_sample_example)
xxx = two_stage_sample_example
head(xxx)
e = xxx$e
t = xxx$t
r = xxx$r
t_star = 10
N_first_stage = c(A = 132, B = 168)
N_first_stage
category = xxx$category
design = list(N_first_stage = N_first_stage, category = category)
epsilon = length(e)^(-1/3)
N_bootstraps = 100
set.seed(2)
individual = rmap_individual(e, t, r, t_star, design, epsilon, N_bootstraps)
pretty_individual_risk_plot(individual)
```

# Weighted

```{r weighted_grouped, fig.height = 5, fig.width = 7}
library(rmap)
data(weighted_example_cohort_sample)
xxx = weighted_example_cohort_sample
head(xxx)
e = xxx$e
t = xxx$t
r = xxx$r
t_star = 10
data(weighted_example_target_sample)
head(weighted_example_target_sample)
target_category = weighted_example_target_sample$category
category = xxx$category
design = list(target_category = target_category, category = category)
cutoffs = c(0, 0.20, 1)
epsilon = length(e)^(-1/3)
N_bootstraps = 100
set.seed(3)
individual = rmap_individual(e, t, r, t_star, design, epsilon, N_bootstraps)
pretty_individual_risk_plot(individual)
```


