---
title: "score-statistics-formula-v01"
author: "Gail Gong"
date: "2013 August 30"
output:
  pdf_document:
    highlight: tango
    number_sections: no
    pandoc_args: --variable=geometry:margin=0.75in
    toc: yes
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
fontsize: 12pt
---
 
```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```
trunk/projects/calibration/07-rmap-v-0.01-06/07-corn-www-rmap/doc/score-statistics-formula-v01.Rmd

Copied from trunk/projects/calibration/04-the-next-rmap-package/03-rmap-v0.01-05-first-try/website-support-material/score-statistics-formulas/score-statistics-formulas-v01.Rmd

# 1. The score statistic

A person's model-assigned risk has the form $r = r(t^{*})$ where 

__Equation (1)__

\begin{align}
r(t^*) = \int_0^{t^{*}} \lambda_1(u) \;\;\text{exp}\Big\{ 
- \Big( \Lambda_1(u) + \Lambda_2(u) \Big) \Big\} du 
\end{align}


and where $\lambda_1$ and $\lambda_2$ denote the model-assigned hazard rates for disease and death respectively.

A person's observed data has the form $\big( t, \varepsilon_1, \varepsilon_2 \big)$;  $t = \text{min} \big(t_1, t_2, c \big)$, where $t_1$ and $t_2$ are her latent times to disease and death respectively, and $c \le t^{*}$ is her time of last observation; $\varepsilon_1 = 1\big(t = t_1\big)$ and $\varepsilon_2 = 1\big(t = t_2 \big)$.

Our goal is to test the null hypothesis that the risk model conforms to the survival data of the people in the cohort study. If this hypothesis is rejected, we want to investigate subsets of people for whom the model fits poorly.

We embed the hypothesized risk model in a larger model involving an unknown parameter vector $\beta$ with the property that $\beta = 0$ when the null hypothesis holds. We use the likelihood-based efficient score for $\beta$ to form a test statistic.


Let $z$ denote a vector of known predictors for the person, for example multinomial subgroups of assigned risks, or simply $z = 1$. The expanded hazards are 

\begin{align}
\lambda_j \big( t ; \beta, z = (z_1, z_2)\big) = \lambda_j (t) e^{\beta_j^T z_j}, \;\;\;j = 1, 2
\end{align}

where $\beta_j$ and $z_j$ are of dimension $K$. 

If times to disease, death, and censoring are independent, the probability of the $n$-th person's observed data is proportional to 

\begin{align}
L_n & = \prod_{j=1}^2 \Bigg\{ \bigg(
\lambda_{nj} \big( t_n \big) e^{\beta_j^T z_{nj}}
\bigg)^{\varepsilon_{nj}}
\text{exp} \bigg(
 \Lambda_{nj}(t_n)  -e^{\beta_j^T z_{nj}}
\bigg) \Bigg\}\\
\end{align}

where

__Equation (2)__

\begin{align}
\Lambda_{nj}(t_n) & = \int_0^t \lambda_{nj}(u) du, \;\;\; n = 1, \cdots, N, \; \; j = 1, 2  
\end{align}

I emphasize here that $\Lambda_{nj}(t_n)$ is evaluated at the **event time**  $t_n$ from the person's observed time $t_n = \text{min}(t_{n1}, t_{n2}, c_n)$. 

The person's contribution to the efficient score (for $j = 1, 2$) is

\begin{align}
U_{nj} = \frac{\partial}{\partial \beta_j} \text{log} L_n(\beta) \bigg|_{\beta_j = 0}
= \bigg\{
\varepsilon_{nj} - e^{\beta^T z_n} \Lambda_{nj}(t_n)
\bigg\} z_{nj} \bigg|_{\beta = 0}
= \bigg\{
\varepsilon_{nj} - \Lambda_{nj}(t_n)
\bigg\} z_{nj} 
\end{align}


And the person's contribution to the variance is

\begin{align}
V_{nj} & =
- \frac{\partial}{\partial \beta_j} \bigg( \frac{\partial}{\partial \beta_j} \bigg)^T
\text{log} L_n(\beta) \bigg|_{\beta_j = 0}
=  e^{\beta_j^T z_{nj}} \Lambda_{nj}(t_n) Z_{nj} Z_{nj}^T \bigg|_{\beta_j = 0}
= \Lambda_{nj}(t_n) Z_{nj} Z_{nj}^T
\end{align}


The score test statistic $T_j$ is


\begin{align}
T_j & = U_j^T V_j^{-1} U_j\\
U_j &= \sum_{n = 1}^N U_{nj}\\
V_j &= \sum_{n = 1}^N V_{nj}
\end{align}


$T_1 = T_{\text{outcome}}$ and $T_2 = T_{\text{mortality}}$ tests the model inadequacy of the outcome hazard and mortality hazard respectively.  We can also obtain $T_+ = T_{\text{combined}}$ that tests the model inadequacy of either hazard by setting $z = z_1 = z_2$ and $\beta = \beta_1 = \beta_2$ above.

The person's contribution to the efficient score is 


\begin{align}
U_{n+} = \frac{\partial}{\partial \beta} \text{log} L_n(\beta) \bigg|_{\beta = 0}
= \bigg\{
\varepsilon_{n+} - e^{\beta^T z_n} \Lambda_{n+}(t_n)
\bigg\} z_n \bigg|_{\beta = 0}
= \bigg\{
\varepsilon_{n+} - \Lambda_{n+}(t_n)
\bigg\} z_n,
\end{align}


the person's contribution to the variance is

\begin{align}
V_{n+} & =
- \frac{\partial}{\partial \beta} \bigg( \frac{\partial}{\partial \beta} \bigg)^T
\text{log} L_n(\beta) \bigg|_{\beta = 0}
=  e^{\beta^T z_n} \Lambda_{n+}(t_n) Z_n Z_n^T \bigg|_{\beta = 0}
= \Lambda_{n+}(t_n) Z_n Z_n^T
\end{align}

and the test statistic is


\begin{align}
T_+ & = U_+^T V_+^{-1} U_+\\
U_+ &= \sum_{n = 1}^N U_{n+}\\
V_+ &= \sum_{n = 1}^N V_{n+}
\end{align}


# 2. Regression examples

## 2A Example 1: $z_{nj} = 1$
We have $K = 1$ and 

\begin{align}
U_j & = \sum_{n = 1}^N \bigg\{
\varepsilon_{nj} - \Lambda_{nj}(t_n)
\bigg\}\\
V_j & = \sum_{n = 1}^N \Lambda_{nj}(t_n)\\
T_j & = U_j^2/V_j
\end{align}


For the covariate $z = z_1 = z_2$, we obtain the above equations but with $+$ replacing $j$.

## 2B Example 2: $z_{nj} = \frac{\text{exp}(|r_n - \bar{r}|)}{\text{exp}(\text{max}(r_n) - \bar{r})}$
Again $K = 1$ and

\begin{align}
\bar{r} &= \frac{1}{N} \sum_{n = 1}^N r_n\\
U_j &= \sum_{n = 1}^N \bigg\{
\varepsilon_{nj} - \Lambda_{nj}(t_n)
\bigg\} z_n \\
V_j & = \sum_{n = 1}^N \Lambda_{nj}(t_n) z_{nj}^2\\
T_j & = U_j^2/V_j
\end{align}


I emphasize here that $r_n = \int_0^{t^{*}} \lambda_{n1}(u) S_{n1}(u) S_{n2}(u) du$, that is the right hand limit of integration is $t^*$.

For the covariate $z = z_1 = z_2$, we obtain the above equations but with $+$ replacing $j$.

## 2C Example 3: $z_{nj} = \big(z_{nj1}, \cdots, z_{njK} \big)^T$ 

$z_{nj}$ is a multinomial vector of indicators for membership in one of the $K$ subgroups in a partition of the sample.

For simplicity, suppose I have two subgroups (or two quantiles).


\begin{align}
z_{nj}  = \begin{cases} 
   \begin{pmatrix}
      1 \\
      0
   \end{pmatrix} &  \text{ if $n$ is in the first subgroup}\\ 
   \begin{pmatrix}
      0 \\
      1
   \end{pmatrix} & \text{ if $n$ is in the second subgroup }
\end{cases}
\end{align}



\begin{align}
z_{nj} z_{nj}^T = \begin{cases} 
   \begin{pmatrix}
      1 & 0\\
      0 & 0
   \end{pmatrix} &  \text{ if $n$ is in the first subgroup}\\ 
   \begin{pmatrix}
      0 & 0\\
      0 & 1
   \end{pmatrix} & \text{ if $n$ is in the second subgroup }
\end{cases}
\end{align}


And then I can write


\begin{align}
U_j & = \sum_{n=1}^N \bigg\{ \varepsilon_{nj} - \Lambda_{nj}(t_n) \bigg\} z_{nj} 
= \begin{pmatrix}
      \sum_{n \in \text{ Subgroup } 1} \bigg\{ \varepsilon_{nj} - \Lambda_{nj}(t_n) \bigg\}  \\
      \sum_{n \in \text{ Subgroup } 2} \bigg\{ \varepsilon_{nj} - \Lambda_{nj}(t_n) \bigg\} 
   \end{pmatrix} 
\end{align}



\begin{align}
V_j & = \sum_{n=1} \Lambda_{nj}(t_n) z_{nj} z_{nj}^T
= \begin{pmatrix}
      \sum_{n \in \text{ Subgroup } 1} \Lambda_{nj}(t_n) & 0 \\
      0 & \sum_{n \in \text{ Subgroup } 2} \Lambda_{nj}(t_n)
   \end{pmatrix} 
\end{align}


And now I can write the score statistic


\begin{align}
T_j & = U_j^T V_j^{-1} U_j  = \sum_k \frac{\bigg(
\sum_{n \in \text{ Subgroup } k} \bigg\{ \varepsilon_{nj} - \Lambda_{nj}(t_n) \bigg\}
\bigg)^2
}{
\sum_{n \in \text{ Subgroup } k} \Lambda_{nj}(t_n)
}
\end{align}


The $k$-th subgroup-specific residual is 


\begin{align}
\delta_{jk} &= \frac{
\sum_{n \in \text{ Subgroup } k}  \bigg\{ \varepsilon_{nj} - \Lambda_{nj}(t_n) \bigg\}
}{
\sqrt{\sum_{n \in \text{ Subgroup } k} \Lambda_{nj}(t_n)}
}
\end{align}


For the covariate $z = z_1 = z_2$, we obtain the above equations but with $+$ replacing $j$.

