---
title: "101-foodweb"
author: ''
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = FALSE, fig.height = 10, fig.width = 10, tidy=FALSE)
```

`r getwd()`  

"2017-06-23 12:05:27 PDT"


```{r message = FALSE, warning = FALSE, fig.height = 15}
library(mvbutils)

library(rmap)

foodweb(where = "package:rmap", rprune = "rmap", color.lines = FALSE,
        descendents = TRUE, ancestors = FALSE)
```

```{r fig.height = 7}
foodweb(where = "package:rmap", rprune = "rmap_grouped_fn", color.lines = FALSE,
        descendents = TRUE, ancestors = FALSE)
```

```{r fig.height = 5}
foodweb(where = "package:rmap", rprune = "rmap_individual", color.lines = FALSE,
        descendents = TRUE, ancestors = FALSE)
```



```{r}
fw = foodweb(where = "package:rmap", cex = .9)
mat = fw$funmat
funs = dimnames(mat)[[1]]
```


# functions and who they call


```{r}
function_dependencies_0 = sapply(dimnames(mat)[[1]], function(fun){
  names(which(mat[fun,] == 1))
}, simplify = FALSE)
```

```{r}
function_dependencies_0[sapply(function_dependencies_0, length) != 0]
```

# functions who call noone

```{r}
names(function_dependencies_0)[sapply(function_dependencies_0, length) == 0]
```



# functions and who calls them


```{r}

function_dependencies_0 = sapply(dimnames(mat)[[1]], function(fun){
  names(which(mat[, fun] == 1))
}, simplify = FALSE)
```

```{r}
function_dependencies_0[sapply(function_dependencies_0, length) != 0]
```


# functions with no callers

```{r}
names(function_dependencies_0)[sapply(function_dependencies_0, length) == 0]
```



