
---
title: "01_2017-06-04-notes"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: yes
fontsize: 12pt
---
<A NAME="top"> </A>
```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

"2017-06-05 10:52:51 PDT"

I copied this rmap `from 02-rmap-stuff/05-the-current-rmap-was-in-here-i-thought-it-didnt-work-but-now-maybe`

I will copy the R functions from `concordance/concordance/05-beginning-again-with-19-proceed-to-adding-to-rmap/36-rmap-functions-inside-fix-tStar/00-from-05-the-current-rmap-was-in-here-i-thought-it-didnt-work-but-now-maybe` to here and get a git diff to summarize the changes that I made to make the riskValidateGrouped functions working with t bigger than tStar.

02-rmap-stuff/06-rmap-allowing-t-bigger-than-t_star/rmap2 contains changes tor baseArgsFn, df_raw, lambdaHatFn, riskValidate, nad riskValidateExternalFn for reading in t_star instead of having it understood that all the t have been truncated at tStar.

#  I currently have three versions of rmap.  

1. The david version  `07-a-copy-of-05-at-v2pt1_here_just_to_compare_changes/david` copied from   `02-rmap-stuff/05-the-current-rmap-was-in-here-i-thought-it-didnt-work-but-now-maybe`

2. rmap2, which is david changed so riskValidate works with t bigger than t_star, and t_star input separately.  `06-rmap-allowing-t-bigger-than-t_star/rmap2`

3. 36-rmap-functions-inside-fix-tStar which is david changed so that riskValidateGrouped works

# These are being implemented in `concordance/concordance`

`05-beginning-again-with-19-proceed-to-adding-to-rmap/37-ground-zero-runs-using-david-rmap/01-ground-zero-runs-using-david-rmap/0`

# These are the changes made to  `rmap2`

## `baseArgsFn`

I inserted `t_star` in the arguments
```
baseArgsFn = function(e, t, r, t_star, design, riskGroup, rSummary, bootstrap, multicore = FALSE, verbose = FALSE) {
```

and `t_star` in the output `baseArgs` list

```
t_star = t_star, 
```
I have not removed `tStar` which gets defined inside `riskGroup` when ungrouped is desired

## `df_raw`

The definition of `tEvents` is now

```
  tEvents = matrix(c( 
    rexp(NTotal, eta0),  # GG 2017-05-26 previously, this was truncated at tStar
    rexp(NTotal, eta1),                   
    rexp(NTotal, eta2)), 
    ncol = 3) 
```
The line 
```
rexp(NTotal, eta0),
```
replacing 
```
pmin(rexp(NTotal, eta0), tStar),
```
## `lambdaHatFn`

Replace
```
tau = sort(unique(t_k[e_k != 0]))
```
with
```
tau = sort(unique(t_k[e_k != 0 & t_k < t_star]))  # GG 2017-05-26 this to compensate for allowing t bigger than t_star
```

## `riskValidate` 

Insert `t_star` into its arguments and when it calls `riskValidateExternalFn`

```
-riskValidate = function(e, t, r, design = "randomSample", riskGroup, rSummary, bootstrap = FALSE,
+riskValidate = function(e, t, r, t_star, design = "randomSample", riskGroup, rSummary, bootstrap = FALSE,
                         rvpar = rvparFn()) {
   
-  rv = riskValidateExternalFn(e, t, r, design, riskGroup, rSummary, bootstrap)
+  rv = riskValidateExternalFn(e, t, r, t_star, design, riskGroup, rSummary, bootstrap)
```

## `riskValidateExternalFn`

Insert `t_star` into its arguments and when it calls `baseArgs`
```
-riskValidateExternalFn = function(e, t, r, design = "randomSample", riskGroup, rSummary, bootstrap = FALSE) {
-  baseArgs = baseArgsFn(e, t, r, design, riskGroup, rSummary, bootstrap)
+riskValidateExternalFn = function(e, t, r, t_star, design = "randomSample", riskGroup, rSummary, bootstrap = FALSE) {
+  baseArgs = baseArgsFn(e, t, r, t_star, design, riskGroup, rSummary, bootstrap)
```


# more changes (these are from 36)
## `baseArgsFn`

I will be using instead the `baseArgsFn` from 36 

To get to the version in 36, I deleted the lines from
```
  if( ("ungrouped" %in% names(riskGroup)) && ("tStar" %in% names(riskGroup$ungrouped)) &&
     (any(t > riskGroup$ungrouped$tStar)) ) {
    stop("Please specify tStar to be greater than or equal to your largest value of t.")
  }
```

I added `tStar` to the arguments and replaced the output `tStar = riskGroup$tStar` with just plain `tStar = tStar`.  

To get the 36 version to look the same as the previous rmap2 version, I just return `t_star = tStar`.  I will remove `t_star` shortly.

## `riskValidateUngrouped`

Add `tStar` to the input args and remove `CRP` from `rvu`
```
riskValidateUngrouped = function(
  e, t, r, tStar, design = "randomSample", riskGroup, bootstrap = FALSE,
  rvpar = rvparFn(), multicore = FALSE, verbose = FALSE) {

  rvu = riskValidateUngroupedExternalFn(
    e = e, t = t, r = r, tStar, design = design,
    riskGroup = riskGroup,
    bootstrap = bootstrap, multicore = multicore, verbose = verbose) 
```

## `riskValidateUngroupedExternal`

Add `tStar` to the input args
```
riskValidateUngroupedExternalFn = function(
    e, t, r, tStar, design, riskGroup, bootstrap,
    multicore, verbose) {

  rSummary = "mean"
  baseArgs = baseArgsFn(e = e, t = t, r = r, tStar, design = design,
    riskGroup = riskGroup, rSummary = rSummary, bootstrap = bootstrap,
    multicore = multicore, verbose = verbose)
```

## `riskValidateUngroupedInternal`

Remove `auc` definition
```
  auc = AUCInternalFn(baseArgs = baseArgs, extraArgs = extraArgs)
   rvu = list(AUC = auc)
```

I redefined `baseArgs$e` and `baseArgs$t to reflect truncation at `tStar`. This will imply that AUC will not go through `riskValidateUngrouped`.

Remove `AUC` from `rvu`


```
 riskValidateUngroupedInternalFn = function(baseArgs = FALSE, extraArgs = FALSE) {
-
-  auc = AUCInternalFn(baseArgs = baseArgs, extraArgs = extraArgs)
-  # give us AUC, AUC_CI, and CRP
-
+  e = baseArgs$e
+  t = baseArgs$t
+  tStar = baseArgs$tStar
+  baseArgs$e = ifelse(t > tStar, 0, e)
+  baseArgs$t = ifelse(t > tStar, tStar, t)
   pnn = piHatNNInternalFn(baseArgs = baseArgs, extraArgs = extraArgs)
-
-  rvu = list(AUC = auc, PNN = pnn)
+  rvu = list(PNN = pnn)
 
   class(rvu) = c("rvu", class(rvu))
```
## `rho_piHatNN_Fn`

In the call to `baseArgsFn` I added `tStar` in the input args
```
    baseArgsNN1 = baseArgsFn(
      e = baseArgs$e[NN1],
      t = baseArgs$t[NN1],
      r = baseArgs$r[NN1],
      tStar = baseArgs$tStar,
      design = list(N = tapply(aaa[NN1], names(aaa[NN1]), sum),
        c = baseArgs$c[NN1]),
      riskGroup = list(K = 1),
      rSummary = "mean",
      bootstrap = FALSE)
```
## `print.rvu`

I commented out the part about CRPs
```
-  cat("\nHead of CRP's: \n")
-  print.default(head(rvu$CRP$CRP, n = n))
+  # cat("\nHead of CRP's: \n")
+  # print.default(head(rvu$CRP$CRP, n = n))
```

# I found I had passed in t_star with a global variable

## `lambdaHatFn`

Add this line
```
t_star = baseArgs$t_star
```

## `baseArgsBootFn`

Add `t_star` to the output list
```
t_star = baseArgs$t_star,
```

# Change all `t_star` to `tStar`

## `baseArgsFn` and `baseArgsBootFn`

Remove `t_star` from the output list

## `lambdaHatFn`, `riskValidate`, and `riskValidateExternal`

Change all `t_star` to `tStar`



