---
title: "01-rmap-examples"
author: ''
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 4.5, fig.width = 6.5, tidy=FALSE)
```

"2017-08-05 12:21:37 PDT"




`r getwd()`  

`r Sys.time()`

# Random Sample
```{r random_sample, message = FALSE, eval = TRUE, fig.height = 5, fig.width = 7}
library(rmap)
set.seed(1)
t_star = 10
randomSample = df_randomSample(300)
xxx = randomSample
head(xxx)
e = xxx$e
t = round(xxx$t, 2)
r = round(xxx$r, 4)
random_sample_example = data.frame(e, t, r)
design = "random_sample"
risk_group = list(K = 4)
r_summary = "mean"
N_bootstraps = 100
set.seed(1)
rmap_answers = rmap(e, t, r, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = length(e)^(-1/3)
individual = rmap_individual(e, t, r, t_star, design, epsilon, N_bootstraps)
the_message = paste("rmap on random sample", sep = "\n")
grid.arrange(textGrob(the_message), 
             pretty_risk_plot(rmap_answers), 
             pretty_roc_plot(rmap_answers), 
             pretty_individual_risk_plot(individual),
             ncol = 2)
save(random_sample_example, file = "random_sample_example.RData")
write.csv(random_sample_example, file = "random_sample_example.csv", row.names = FALSE)
```


# Two-stage sample

```{r two_stage_sample, fig.height = 5, fig.width = 7}
set.seed(3)
t_star = 10
NNN = 300
twoStageSample = df_twoStage(NNN)
xxx = twoStageSample$d
e = xxx$e
t = round(xxx$t, 2)
r = round(xxx$r, 4)
c = xxx$c
two_stage_sample_example = data.frame(e, t, r, category = c, stringsAsFactors = FALSE)
N_first_stage = twoStageSample$N
design = list(N_first_stage = N_first_stage, category = xxx$c)
risk_group = list(K = 3)
r_summary = "mean"
N_bootstraps = 100
set.seed(3)
rmap_answers = rmap(e, t, r, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = length(e)^(-1/3)
risk_group = list(epsilon = epsilon)
individual = rmap_individual(e, t, r, t_star, design, risk_group, N_bootstraps)
the_message = paste("rmap on two-stage-sample")
grid.arrange(textGrob(the_message), 
             pretty_risk_plot(rmap_answers), 
             pretty_roc_plot(rmap_answers), 
             pretty_individual_risk_plot(individual),
             ncol = 2)
save(two_stage_sample_example, file = "two_stage_sample_example.RData")
write.csv(two_stage_sample_example, file = "two_stage_sample_example.csv", row.names = FALSE)
save(N_first_stage, file = "N_first_stage.RData")
```

# Weighted

```{r weighted, fig.height = 5, fig.width = 7}
set.seed(5)
NNN = 400
N_bootstraps = 100
cutoffs = c(0, 0.20, 1)
weighted_example = weighted_example_fn(NNN)
cohort_sampling_probability_dictionary = weighted_example$cohort_sampling_probability_dictionary
cohort_sample = weighted_example$cohort_sample
target_sample = weighted_example$target_sample
head(target_sample)
t_star = weighted_example$t_star
which_model = "r_B" 
cohort_category = cohort_sample$category
target_category = target_sample$category
r = round(cohort_sample[[which_model]], 4)
e = cohort_sample$eee
t = round(cohort_sample$ttt, 2)
weighted_example_cohort_sample = data.frame(e, t, r, category = cohort_category, stringsAsFactors = FALSE)
weighted_example_target_sample = target_sample[, c("x_1", "x_2", "category")]
design = list(target_category = target_category, category = cohort_category)
risk_group = list(cutoffs = cutoffs)
r_summary = "mean"
set.seed(5)
rmap_answers = rmap(e, t, r, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = length(e)^(-1/3)
risk_group = list(epsilon = epsilon)
individual = rmap_individual(e, t, r, t_star, design, risk_group, N_bootstraps)
the_message = paste("rmap on weighted sample")
grid.arrange(textGrob(the_message), 
             pretty_risk_plot(rmap_answers), 
             pretty_roc_plot(rmap_answers), 
             pretty_individual_risk_plot(individual),
             ncol = 2)
save(weighted_example_cohort_sample, file = "weighted_example_cohort_sample.RData")
write.csv(weighted_example_cohort_sample, file = "weighted_example_cohort_sample.csv", row.names = FALSE)
save(weighted_example_target_sample, file = "weighted_example_target_sample.RData")
write.csv(weighted_example_target_sample, file = "weighted_example_target_sample.csv", row.names = FALSE)
```


# Comparing two risk models using composite plots

```{r comparing}
set.seed(7)
xxx =  df_randomSample_r1_r2()
head(xxx)
e = xxx$e
t = round(xxx$t, 2)
r1 = round(xxx$r1, 4)
r2 = round(xxx$r2, 4)
two_model_comparison_example = data.frame(e, t, r1, r2)
t_star = 10
design = "random_sample"
risk_group = list(K = 4)
r_summary = "mean"
N_bootstraps = 100
set.seed(7)
rmap_1 = rmap(e, t, r1, t_star, design, risk_group, r_summary, N_bootstraps)
rmap_2 = rmap(e, t, r2, t_star, design, risk_group, r_summary, N_bootstraps)
epsilon = nrow(xxx)^(-1/3)
risk_group = list(epsilon = epsilon)
individual_1 = rmap_individual(e, t, r1, t_star, design, risk_group, N_bootstraps)
individual_2 = rmap_individual(e, t, r1, t_star, design, risk_group, N_bootstraps)
rmap_1$numerical_summaries
names(rmap_1$plots)
names(individual_1)
roc_1 = rmap_1$plots$df_for_roc_plot
roc_2 = rmap_2$plots$df_for_roc_plot
head(roc_1)
roc_1$model = rep("Model 1 is super duper", nrow(roc_1))
roc_2$model = rep("Model 2", nrow(roc_2))
df = rbind(roc_1, roc_2)
ggplot(df, aes(x = one_minus_specificity, y = sensitivity, color = model)) +
  geom_step() + 
  geom_abline(slope = 1, intercept = 0, color = "gray", linetype = 2) +
  scale_color_manual(values = c("blue", "red")) +
  theme(legend.title = element_blank()) +
  theme(legend.position = c(0.2, 0.9)) +
  ggtitle("ROC plots for assigned risk Models 1 and 2")
p1 = rmap_1$plots$risk_plot + ggtitle("Zee Model One")
p2 = rmap_2$plots$risk_plot + ggtitle("Yep this is Model Two")
p3 = individual_1$risk_plot
p4 = individual_2$risk_plot
grobs = lapply(list(p1, p2, p3, p4), `+`, 
               theme(axis.title = element_blank(),
                     plot.title = element_text(hjust = 0.5)))
space = .5
grid.arrange(grobs[[1]] + theme( axis.text.x = element_blank(),
                                 plot.margin = unit(c(space,0,0,space), "cm")),
             grobs[[2]] + theme( axis.text = element_blank(),
                                 plot.margin = unit(c(space,space,0,0), "cm")),
             grobs[[3]] + theme( plot.margin = unit(c(0,0,space,space), "cm")), 
             grobs[[4]] + theme( axis.text.y = element_blank(),
                                 plot.margin = unit(c(0,space,space,0), "cm")), 
             left = "Observed Risks (%)",
             bottom = "Assigned Risks (%)",
             top = "Attribute and Individualized Attribute Diagrams for Models 1 and 2",
             ncol = 2)
save(two_model_comparison_example, file = "two_model_comparison_example.RData")
write.csv(two_model_comparison_example, file = "two_model_comparison_example.csv", row.names = FALSE)
```






