#' Generate the data required to showcase weighted rmap
#'
#' Weighted rmap requires a cohort sample with columns
#' `\code{e}, \code{t}, \code{r}, \code{category}
#' as well as a vector of target categories.
#' This function generates such data.
#' For the risk vector \code{r}, you may choose between
#' \code{r_A} equal to the true probability of disease
#' and \code{r_B} a probability that accounts for
#' only half the effect of the covariate \code{x_2}
#' which is one of the two covariates both determining
#' disease and defining the \code{category} vector.
#' Cohort and target samples are obtained via calls
#' to \code{cohort_fn} with different
#' versions of the parameter \code{sampling_probability_dictionary}
#'
#' @param NNN A positive integer defining how many people are
#' generated by the random sample before oversampling and
#' oversampling.
#'
#' @return A list containing
#' (a) \code{cohort_sampling_probability_dictionary}, a named vector
#' showing the sampling probabilities used,
#' (b) \code{cohort_sample} A data.frame containing columns
#' \code{x_1}, \code{x_2}, \code{category},
#' \code{sam} (the sampling probability), \code{r_A}, \code{r_B}, \code{t_0},
#' \code{t_1}, \code{ttt}, \code{eee},
#' (c) \code{target_sample} A data.frame containing columns of the same
#' names as those of \code{cohort_sample} gotten in the same way as
#' \code{cohort_sample} but with \code{sampling_probability_dictionary}
#' values all unity,
#' (d) \code{t_star} The right end point of duration of study,
#' used to define \code{r_A} and \code{r_B}.
#'
#' @examples
#' NNN = 13
#' weighted_example_fn(NNN)
#'
#' @export
weighted_example_fn = function(NNN){
  x_digits = 2
  t_digits = 2
  t_star = 10
  cohort_sampling_probability_dictionary =
    cohort_2_sampling_probability_dictionary = c(A = 1, B = 0.05, C = 1,    D = 0.05)
  target_sampling_probability_dictionary = c(A = 1, B = 1,    C = 1,    D = 1)
  survival_data = FALSE
  target_sample = cohort_fn(
    NNN, target_sampling_probability_dictionary, survival_data, t_star, x_digits, t_digits)
  cohort_sample = cohort_fn(
    NNN, cohort_sampling_probability_dictionary, survival_data, t_star, x_digits, t_digits)
  list(
    cohort_sampling_probability_dictionary = cohort_sampling_probability_dictionary,
    cohort_sample = cohort_sample,
    target_sample = target_sample,
    t_star = t_star)
}
